#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
	sleep 60 # wait system network ok 
	chmod +x /etc/webPlugin/clean_sub.sh
	chmod +x /etc/webPlugin/conf.sh

	echo service webPlugin start

	procd_open_instance
	procd_set_param command webPlugin
	procd_set_param respawn
	procd_close_instance

}
